# Generated by Django 5.1.4 on 2025-01-08 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_profile_old_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='date_modified',
            new_name='date',
        ),
    ]
