# Generated by Django 5.1.4 on 2025-01-08 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_date_modified_profile_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='date',
            new_name='date_modified',
        ),
    ]
